# Generated by Django 3.1.1 on 2020-09-20 23:20

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='close_time',
        ),
        migrations.AddField(
            model_name='listing',
            name='expire_time',
            field=models.DateTimeField(default=auctions.models.set_default_datetime, editable=False),
        ),
        migrations.AlterField(
            model_name='bid',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
