# Generated by Django 3.1.1 on 2020-09-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200921_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='closed',
        ),
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.IntegerField(choices=[(0, ''), (1, 'Fashion'), (2, 'Toys'), (3, 'Electronics'), (4, 'Home')], default=0),
        ),
    ]
